name: minima
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:
  path_provider:
  path:
  cupertino_icons:
  flutter_svg:
  transition:
  kakao_flutter_sdk:
  toast:
  http:
  flutter_rating_bar:
  intl:
  auto_size_text:
  tuple:
  cached_network_image:
  loading_animation_widget:
  page_view_indicators:
  shimmer:
  flutter_markdown:
  kpostal:
  syncfusion_flutter_datepicker:
  image_picker:
  flutter_local_notifications:
  workmanager:
  webview_flutter:
  image:
  flutter_time_picker_spinner:
  device_info_plus:
  bootstrap_icons:
  fluentui_system_icons:
  google_sign_in:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/html/
    - assets/images/
    - assets/images/dummy/
    - assets/images/icons/
    - assets/images/icons/social/


  fonts:
    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo/thin.otf
          weight: 100
        - asset: assets/fonts/SpoqaHanSansNeo/light.otf
          weight: 300
        - asset: assets/fonts/SpoqaHanSansNeo/regular.otf
          weight: 400
        - asset: assets/fonts/SpoqaHanSansNeo/medium.otf
          weight: 500
        - asset: assets/fonts/SpoqaHanSansNeo/bold.otf
          weight: 700
    - family: SegoeUIEmoji
      fonts:
        - asset: assets/fonts/SegoeUIEmoji/default.ttf

flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path: "assets/images/icons/app-icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icons/app-icon.png"