name: minima
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:
  path_provider:
  path:
  cupertino_icons: ^1.0.2
  flutter_svg:
  transition:
  kakao_flutter_sdk:
  toast:
  http:
  flutter_rating_bar:
  intl:
  auto_size_text:
  tuple:
  cached_network_image:
  loading_animation_widget:
  page_view_indicators:
  shimmer:
  flutter_markdown:
  kpostal:
  syncfusion_flutter_datepicker:
  image_picker:
  flutter_local_notifications:
  workmanager:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/dummy/
    - assets/images/icons/
    - assets/images/icons/social/


  fonts:
    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo/thin.otf
          weight: 100
        - asset: assets/fonts/SpoqaHanSansNeo/light.otf
          weight: 300
        - asset: assets/fonts/SpoqaHanSansNeo/regular.otf
          weight: 400
        - asset: assets/fonts/SpoqaHanSansNeo/medium.otf
          weight: 500
        - asset: assets/fonts/SpoqaHanSansNeo/bold.otf
          weight: 700
    - family: SegoeUIEmoji
      fonts:
        - asset: assets/fonts/SegoeUIEmoji/default.ttf

